def instructions 
    print("Rock-Paper-Scissors is a game played to settle disputes between two people. ")
    print("Thought to be a game of chance that depends on random luck similar to flipping coins or drawing straws, ")
    print("the game is often taught to children to help them settle arguments between themselves on their own without adult intervention. ")
    print("However, the game actually can be a game that has an element of skill that requires quick thinking and perceptive reasoning.1")
    print("The game is played with three possible hand signals that represent a rock, paper, and scissors. The rock is a closed fist; ")
    print("paper is a flat hand with fingers and thumb extended and the palm facing downward; and scissors is a fist with the index ")
    print("and middle fingers fully extended toward the opposing player. Rock wins against scissors; paper wins against rock; ")
    print("and scissors wins against paper. If both players throw the same hand signal, it is considered a tie, ")
    print("and play resumes until there is a clear winner.")
    print("The hand signals are given simultaneously by both players")
    rockmenu()